# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SocialTopography
                                 A QGIS plugin
 Geographic tool that converts values to smooth hills and vallyes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-27
        copyright            : (C) 2023 by Orange Cube
        email                : shai.sussman@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SocialTopography class from file SocialTopography.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .social_topography import SocialTopography
    return SocialTopography(iface)
